### ISSUE TITLE
o2r.info sidebar is not displayed correctly

### ISSUE THREAD

**Issue by LukasLohoff** [o2r-project/o2r-project.github.io#18]
When viewing the o2r.info website with a small resolution (for example 1280x800) the sidebar is not completely displayed and not scrollable:

![o2r_website_sidebar](https://user-images.githubusercontent.com/5795523/29922119-873cf048-8e54-11e7-8437-c11d63a7bdd9.png)

**Comment by 7048730** [comment]
https://www.w3schools.com/browsers/browsers_display.asp

**Comment by nuest** [comment]
It is very hard to scale a website based on the browser height. I decreased the font size of the tagline (which is quite long anyway) and removed the space within the menu, so that the sidebar is almost fully visible even at 600px height, which should cover th most common desktop sizes (considering space for toolbars etc.):

![image](https://user-images.githubusercontent.com/1325054/29963791-5b2c92e2-8f08-11e7-9507-2e1087b785f4.png)
