### ISSUE TITLE
Evaluate switch away from Discuss for issues

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-project.github.io#33]
Less data collection and no third party accounts: https://staticman.net/

**Comment by VincentTam** [comment]
Disqus has a plethora of downsides.

1. Heavy weight
2. Privacy problems
3. not SEO-friendly

Here're some articles about replacing Disqus.

1. https://victorzhou.com/blog/replacing-disqus/
2. https://old.reddit.com/r/programming/comments/b9022a/switching_off_of_disqus_reduced_my_page_weight_by/

Nonetheless, none of these mentioned static comments, whose upsides include:

1. total ownership of comments stored as site data
2. SEO-friendly
3. quicker load time, since data files are converted into HTML tags by static site generator

The benefits of total ownership means one can render comments in whatever way one wants, say math and nested comments support.

![math equation in comments](https://camo.githubusercontent.com/60e914a9c5de08ad7b547036f9336361c37acba8/687474703a2f2f696d6775722e636f6d2f4b5254744a4c586c2e706e67)  
Site: https://staticman-gitlab-pages.frama.io/bhdemo/

P.S. I built @staticmanlab.

**Comment by nuest** [comment]
**Another alternative**: https://utteranc.es/

**Comment by VincentTam** [comment]
In utterances, comments are loaded into the site via JavaScripts, so they can't be searched by search bots.  Comments are part of the site's content, and they might add value to the site, so it's a good idea to make them searchable by search engines.

**Comment by nuest** [comment]
One more, and possibly the best, option: Isso - https://posativ.org/isso/
We can host that on o2r.uni-muenster.de.

**Comment by nuest** [comment]
Discuss disabled in https://github.com/o2r-project/o2r-project.github.io/pull/73

**Comment by nuest** [comment]
We had so few discussions even when Discuss was running - we probably don't need this.
